# ==============================================================================
# => psql database container
FROM postgres:9.6.9 as postgres

RUN mkdir -p /app/pgdata && chown -R postgres:postgres /app
