# ==============================================================================
# => psql database container
FROM postgres:12.8 as postgres

RUN mkdir -p /app/pgdata && chown -R postgres:postgres /app
