# => Build container
FROM node:14.4.0 as dev

# Set working directory
WORKDIR /app

COPY package*.json ./

RUN npm install --silent

RUN npm install react-scripts@3.4.1 -g --silent

COPY . .

CMD ["npm", "start"]
