# Generated by Django 2.2.13 on 2020-09-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0002_fmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True,
                        help_text="Please use the two character state abbreviation",
                        max_length=2,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="The 4-digit year of the ACS"
                    ),
                ),
                (
                    "number_uninsured",
                    models.IntegerField(
                        help_text="the number of uninsured children under 200% FPL"
                    ),
                ),
                (
                    "number_uninsured_moe",
                    models.IntegerField(
                        help_text="the margin of error for the number of uninsured children"
                    ),
                ),
                (
                    "percent_uninsured",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="percentage of uninsured     children",
                        max_digits=5,
                    ),
                ),
                (
                    "percent_uninsured_moe",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="the margin of error     for the percentage of uninsured children",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
