# Generated by Django 2.2.13 on 2020-09-21 00:58
from pathlib import Path
import json

from django.db import migrations, models  # type: ignore
import django.db.models.deletion  # type: ignore


def populate_state_data(apps, schema_editor):
    State = apps.get_model("carts_api", "State")
    here = Path(__file__).parent.resolve()
    section_schemas = here.parent.parent.parent / "utils" / "section-schemas"

    state_to_abbrev = json.loads(
        Path(section_schemas, "state_to_abbrev.json").read_text()
    )
    for name, abbrev in state_to_abbrev.items():
        new_state = State.objects.create(code=abbrev, name=name)
        new_state.save()


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0003_acs"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="A unique two-character state code",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full state name", max_length=100
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_state_data),
        migrations.AlterField(
            model_name="acs",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="carts_api.State",
            ),
        ),
        migrations.AlterField(
            model_name="fmap",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="carts_api.State",
            ),
        ),
    ]
