# Generated by Django 2.2.13 on 2020-09-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0003_acs'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(help_text='A unique two-character state code', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full state name', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='acs',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts_api.State'),
        ),
        migrations.AlterField(
            model_name='fmap',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts_api.State'),
        ),
    ]
