# Generated by Django 2.2.13 on 2020-10-02 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0006_new_state_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='eua_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts_api.State'),
        ),
    ]
