# Generated by Django 2.2.13 on 2020-10-08 03:11

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0008_appuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateFromUsername",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("state_code", models.CharField(max_length=2)),
            ],
        ),
    ]
