# Generated by Django 2.2.13 on 2020-10-09 08:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0010_statestatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatesFromUsername",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                (
                    "state_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=2), size=None
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StateFromUsername",
        ),
        migrations.AddField(
            model_name="appuser",
            name="states",
            field=models.ManyToManyField(to="carts_api.State"),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appusers",
                to="carts_api.State",
            ),
        ),
    ]
