# Generated by Django 2.2.13 on 2020-10-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0010_statestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='statestatus',
            name='user_name',
            field=models.TextField(null=True),
        ),
    ]
