# Generated by Django 2.2.13 on 2020-10-13 18:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0011_auto_20201009_0825"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleFromUsername",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("user_role", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="RoleFromJobCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_code", models.CharField(max_length=64, unique=True)),
                ("user_role", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="statesfromusername",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
