# Generated by Django 2.2.13 on 2020-10-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0012_auto_20201013_1824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin_user", "Admin User"),
                    ("bus_user", "Central Office Business Owner"),
                    ("co_user", "Central Office User"),
                    ("state_user", "State User"),
                    ("temp_user", "Temporary User"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rolefromjobcode",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("admin_user", "Admin User"),
                    ("bus_user", "Central Office Business Owner"),
                    ("co_user", "Central Office User"),
                    ("state_user", "State User"),
                    ("temp_user", "Temporary User"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="rolefromusername",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("admin_user", "Admin User"),
                    ("bus_user", "Central Office Business Owner"),
                    ("co_user", "Central Office User"),
                    ("state_user", "State User"),
                    ("temp_user", "Temporary User"),
                ],
                max_length=64,
            ),
        ),
    ]
