# Generated by Django 2.2.13 on 2020-10-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0014_rolesfromjobcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="statestatus",
            name="user_name",
            field=models.TextField(null=True),
        ),
    ]
