# Generated by Django 2.2.13 on 2020-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0015_statestatus_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("in_progress", "In progress"),
                    ("certified", "Certified"),
                    ("uncertified", "Uncertified"),
                    ("approved", "Approved"),
                    ("submitted", "Submitted"),
                    ("published", "Published"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
    ]
