# Generated by Django 2.2.13 on 2020-11-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts_api", "0016_auto_20201016_2114"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("user_role", models.CharField(max_length=100)),
                ("state_codes", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "vw_userprofile",
                "managed": False,
            },
        ),
    ]
