# Generated by Django 2.2.13 on 2020-11-17 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts_api", "0016_auto_20201016_2114"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=256)),
                ("aws_filename", models.CharField(max_length=256)),
                ("question_id", models.CharField(max_length=16)),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("uploaded_username", models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="username",
        ),
        migrations.AddField(
            model_name="appuser",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
