# Generated by Django 2.2.13 on 2021-09-02 20:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts_api', '0020_formtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='contents',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
